<?php
function DCAPI_plugin_override() {

//---------------------------------
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55559b16386c7',
	'title' => 'DCAPI configuration',
	'fields' => array (
		array (
			'key' => 'field_55995544dab88',
			'label' => 'Main',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5588753c1f0a8',
			'label' => 'Site name',
			'name' => 'site_name',
			'type' => 'text',
			'instructions' => 'The name of the site',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => 'DCAPI',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_565e0e4c57a88',
			'label' => 'Base URL',
			'name' => 'base_url',
			'type' => 'url',
			'instructions' => 'The base URL for external routes, starting \'http://\' and ending in a forward slash character. If no value is supplied, then the Wordpress site URL is used and any trailing \'wordpress\' part is removed',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 45,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5717e263d8e67',
			'label' => 'Timeout limit',
			'name' => 'timeout_limit',
			'type' => 'number',
			'instructions' => 'Maximum processing time allowed for a multiple blob process, in seconds',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 15,
				'class' => '',
				'id' => '',
			),
			'default_value' => 30,
			'placeholder' => 30,
			'prepend' => '',
			'append' => '',
			'min' => 15,
			'max' => 60,
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57adc7fc49301',
			'label' => 'Cron update',
			'name' => 'cron_update',
			'type' => 'true_false',
			'instructions' => 'Tick if a regular ^cron job (say, every 5 minutes) is used to update entries',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 15,
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5620dc3624782',
			'label' => 'Visibility',
			'name' => 'visibility',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5620dc7624783',
			'label' => 'Reveal to',
			'name' => 'reveal_to',
			'type' => 'checkbox',
			'instructions' => 'Reveal hidden categories and fields to users with these roles. Hidden categories and fields are always revealed to Administrators',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Editor' => 'Editor',
				'Author' => 'Author',
				'Contributor' => 'Contributor',
				'Subscriber' => 'Subscriber',
			),
			'default_value' => array (
				'administrator' => 'administrator',
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
		array (
			'key' => 'field_5620dd3024784',
			'label' => 'Hidden categories',
			'name' => 'hidden_categories',
			'type' => 'select',
			'instructions' => 'Hide posts with these categories',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'(ohne Kategorie) {category}' => '(ohne Kategorie) {category}',
				'3. bis 8. Klasse {category}' => '3. bis 8. Klasse {category}',
				'Ausflüge und Reisen {category}' => 'Ausflüge und Reisen {category}',
				'Bildung und Begegnung {category}' => 'Bildung und Begegnung {category}',
				'Chöre {category}' => 'Chöre {category}',
				'Conacher-Orgel {category}' => 'Conacher-Orgel {category}',
				'Diakonie {category}' => 'Diakonie {category}',
				'Drucksachen {category}' => 'Drucksachen {category}',
				'Erwachsene {category}' => 'Erwachsene {category}',
				'Eucharistiefeier {category}' => 'Eucharistiefeier {category}',
				'Feiern im Lebenskreis {category}' => 'Feiern im Lebenskreis {category}',
				'Fiire mit de Chind {category}' => 'Fiire mit de Chind {category}',
				'Forum Predigerkirche {category}' => 'Forum Predigerkirche {category}',
				'Freitagsvesper {category}' => 'Freitagsvesper {category}',
				'Gemeindeseite {category}' => 'Gemeindeseite {category}',
				'Geselliges {category}' => 'Geselliges {category}',
				'Glanzpunkte {category}' => 'Glanzpunkte {category}',
				'Gottesdienst mit Abendmahl {category}' => 'Gottesdienst mit Abendmahl {category}',
				'Gottesdienst {category}' => 'Gottesdienst {category}',
				'Gottesdienste (Überbegriff) {category}' => 'Gottesdienste (Überbegriff) {category}',
				'Haus zum Palmbaum {category}' => 'Haus zum Palmbaum {category}',
				'Im Pfrundhaus {category}' => 'Im Pfrundhaus {category}',
				'Inscriptum {category}' => 'Inscriptum {category}',
				'Instrumente {category}' => 'Instrumente {category}',
				'Jahresberichte {category}' => 'Jahresberichte {category}',
				'Jahreskreis {category}' => 'Jahreskreis {category}',
				'Jugendtreff {category}' => 'Jugendtreff {category}',
				'Kantor {person-category}' => 'Kantor {person-category}',
				'Kantorei zu Predigern {category}' => 'Kantorei zu Predigern {category}',
				'Kinder und Jugendliche {category}' => 'Kinder und Jugendliche {category}',
				'Kirche {location-category}' => 'Kirche {location-category}',
				'Kirchenlieder {category}' => 'Kirchenlieder {category}',
				'Kirchenpflege {person-category}' => 'Kirchenpflege {person-category}',
				'Konfirmation {category}' => 'Konfirmation {category}',
				'Konzerte {category}' => 'Konzerte {category}',
				'Kuhn-Orgel {category}' => 'Kuhn-Orgel {category}',
				'Landeskirche {category}' => 'Landeskirche {category}',
				'Leitbild {category}' => 'Leitbild {category}',
				'Lesegruppe {category}' => 'Lesegruppe {category}',
				'Mushafen {category}' => 'Mushafen {category}',
				'Musical {category}' => 'Musical {category}',
				'Musik {category}' => 'Musik {category}',
				'Musiker {person-category}' => 'Musiker {person-category}',
				'Neuigkeiten {category}' => 'Neuigkeiten {category}',
				'Organist {person-category}' => 'Organist {person-category}',
				'Ostern {category}' => 'Ostern {category}',
				'Pfarrperson {person-category}' => 'Pfarrperson {person-category}',
				'Pfingsten {category}' => 'Pfingsten {category}',
				'Prediger Manufaktur {category}' => 'Prediger Manufaktur {category}',
				'Prediger Standorte {location-category}' => 'Prediger Standorte {location-category}',
				'Predigerkirche im Pfrundhaus {category}' => 'Predigerkirche im Pfrundhaus {category}',
				'Projekte {category}' => 'Projekte {category}',
				'Reisen durch Zeit und Raum {category}' => 'Reisen durch Zeit und Raum {category}',
				'Rituale im Jahreskreis {category}' => 'Rituale im Jahreskreis {category}',
				'Seelsorge {category}' => 'Seelsorge {category}',
				'Sekretariat {person-category}' => 'Sekretariat {person-category}',
				'Sigrist/In {person-category}' => 'Sigrist/In {person-category}',
				'Sonntagsgottesdienste {category}' => 'Sonntagsgottesdienste {category}',
				'Sonntagskantor {person-category}' => 'Sonntagskantor {person-category}',
				'Sonntagskantorei {category}' => 'Sonntagskantorei {category}',
				'Sozialdienst {person-category}' => 'Sozialdienst {person-category}',
				'Südsudan {category}' => 'Südsudan {category}',
				'Tagzeitengebet {category}' => 'Tagzeitengebet {category}',
				'Wandern auf ebenen Pfaden {category}' => 'Wandern auf ebenen Pfaden {category}',
				'Weihnachten und Neujahr {category}' => 'Weihnachten und Neujahr {category}',
				'Ökumenischer Gottesdienst mit Abendmahl {category}' => 'Ökumenischer Gottesdienst mit Abendmahl {category}',
				'Ökumenischer Gottesdienst {category}' => 'Ökumenischer Gottesdienst {category}',
			),
			'default_value' => array (
			),
			'allow_null' => 1,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55995449ff44c',
			'label' => 'Back End',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55995460ff44d',
			'label' => 'Date/Status Column Title',
			'name' => 'date_status_column_title',
			'type' => 'text',
			'instructions' => 'If present, then a Date/Status column is created with the given title which overrides the normal Date column',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_559954cc23015',
			'label' => 'Info Column Title',
			'name' => 'info_column_title',
			'type' => 'text',
			'instructions' => 'If present, then an additional information column is created with the given title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'dcapiconfig',
			),
		),
	),
	'menu_order' => 90,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56354aa5f0115',
	'title' => 'Blob data',
	'fields' => array (
		array (
			'key' => 'field_55436c4cc5392',
			'label' => 'Main settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55e5ee1ee3315',
			'label' => 'Blob type',
			'name' => 'blob_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'home' => 'home',
				'home-page' => 'home-page',
				'page' => 'page',
				'post' => 'post',
				'config' => 'config',
				'search' => 'search',
				'clone' => 'clone',
			),
			'default_value' => array (
				0 => 'post',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_553d41c218398',
			'label' => 'Post type',
			'name' => 'post_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'page',
					),
				),
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'post',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'option' => 'option',
				'post' => 'post',
				'page' => 'page',
				'attachment' => 'attachment',
				'person' => 'person',
				'location' => 'location',
			),
			'default_value' => array (
				0 => 'option',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_553fd83c93f12',
			'label' => 'Taxonomy',
			'name' => 'taxonomy',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_553d41c218398',
						'operator' => '!=',
						'value' => 'option',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'category' => 'category',
				'person-category' => 'person-category',
				'location-category' => 'location-category',
			),
			'default_value' => array (
				0 => 'category',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_561410e3b0377',
			'label' => 'Prefix',
			'name' => 'prefix',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '!=',
						'value' => 'home',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '!=',
						'value' => 'home-page',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56141290b0378',
			'label' => 'Home page',
			'name' => 'home_page',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'home-page',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array (
			'key' => 'field_554377a4c107a',
			'label' => 'Has feed',
			'name' => 'has_feed',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'page',
					),
				),
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'home',
					),
				),
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'search',
					),
				),
			),
			'wrapper' => array (
				'width' => 10,
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_55462f766ff05',
			'label' => 'Is cached',
			'name' => 'is_cached',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '!=',
						'value' => 'home-page',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '!=',
						'value' => 'search',
					),
				),
			),
			'wrapper' => array (
				'width' => 10,
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
		),
		array (
			'key' => 'field_5543de13b2844',
			'label' => 'Repeating field',
			'name' => 'repeating_field',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'post',
					),
				),
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'clone',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
			),
			'default_value' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_576e8b5ca08ea',
			'label' => 'Target term',
			'name' => 'target_term',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'clone',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'(ohne Kategorie) {category}' => '(ohne Kategorie) {category}',
				'3. bis 8. Klasse {category}' => '3. bis 8. Klasse {category}',
				'Administration {person-category}' => 'Administration {person-category}',
				'Ausflüge und Reisen {category}' => 'Ausflüge und Reisen {category}',
				'Ausstellungen {category}' => 'Ausstellungen {category}',
				'Bildung und Begegnung {category}' => 'Bildung und Begegnung {category}',
				'Chöre {category}' => 'Chöre {category}',
				'Conacher-Orgel {category}' => 'Conacher-Orgel {category}',
				'Der neue Abendgottesdienst {category}' => 'Der neue Abendgottesdienst {category}',
				'Diakonie {category}' => 'Diakonie {category}',
				'Drucksachen {category}' => 'Drucksachen {category}',
				'Eltern-Kind-Singen {category}' => 'Eltern-Kind-Singen {category}',
				'Erwachsene {category}' => 'Erwachsene {category}',
				'Eucharistiefeier {category}' => 'Eucharistiefeier {category}',
				'Feiern im Lebenskreis {category}' => 'Feiern im Lebenskreis {category}',
				'Fiire mit de Chind {category}' => 'Fiire mit de Chind {category}',
				'Flyer {category}' => 'Flyer {category}',
				'Freitagsvesper {category}' => 'Freitagsvesper {category}',
				'Gemeindeseite {category}' => 'Gemeindeseite {category}',
				'Geschichtliches {category}' => 'Geschichtliches {category}',
				'Geselliges {category}' => 'Geselliges {category}',
				'Glanzpunkte {category}' => 'Glanzpunkte {category}',
				'Gottesdienst mit Abendmahl {category}' => 'Gottesdienst mit Abendmahl {category}',
				'Gottesdienst {category}' => 'Gottesdienst {category}',
				'Gottesdienste (Überbegriff) {category}' => 'Gottesdienste (Überbegriff) {category}',
				'Haus zum Palmbaum {category}' => 'Haus zum Palmbaum {category}',
				'Im Pfrundhaus {category}' => 'Im Pfrundhaus {category}',
				'Inscriptum {category}' => 'Inscriptum {category}',
				'Instrumente {category}' => 'Instrumente {category}',
				'Jahresberichte {category}' => 'Jahresberichte {category}',
				'Jahreskreis {category}' => 'Jahreskreis {category}',
				'Jugendtreff {category}' => 'Jugendtreff {category}',
				'Kantor {person-category}' => 'Kantor {person-category}',
				'Kantorei zu Predigern {category}' => 'Kantorei zu Predigern {category}',
				'Katechetin {person-category}' => 'Katechetin {person-category}',
				'Kinder und Jugendliche {category}' => 'Kinder und Jugendliche {category}',
				'Kirche {location-category}' => 'Kirche {location-category}',
				'Kirchenlieder {category}' => 'Kirchenlieder {category}',
				'Kirchenpflege {person-category}' => 'Kirchenpflege {person-category}',
				'Komplet {category}' => 'Komplet {category}',
				'Konfirmation {category}' => 'Konfirmation {category}',
				'Konzerte {category}' => 'Konzerte {category}',
				'Kuhn-Orgel {category}' => 'Kuhn-Orgel {category}',
				'Landeskirche {category}' => 'Landeskirche {category}',
				'Leitbild {category}' => 'Leitbild {category}',
				'Lesegruppe {category}' => 'Lesegruppe {category}',
				'Mittagsgebet {category}' => 'Mittagsgebet {category}',
				'Mushafen {category}' => 'Mushafen {category}',
				'Musical {category}' => 'Musical {category}',
				'Musik mittendrin {category}' => 'Musik mittendrin {category}',
				'Musik {category}' => 'Musik {category}',
				'Musiker {person-category}' => 'Musiker {person-category}',
				'Neuigkeiten {category}' => 'Neuigkeiten {category}',
				'Organist {person-category}' => 'Organist {person-category}',
				'Orgelprojekt {category}' => 'Orgelprojekt {category}',
				'Ostern {category}' => 'Ostern {category}',
				'Pfarrperson {person-category}' => 'Pfarrperson {person-category}',
				'Pfingsten {category}' => 'Pfingsten {category}',
				'Politik {category}' => 'Politik {category}',
				'Prediger Manufaktur {category}' => 'Prediger Manufaktur {category}',
				'Prediger Standorte {location-category}' => 'Prediger Standorte {location-category}',
				'Predigerforum {person-category}' => 'Predigerforum {person-category}',
				'Predigerkirche (Musik mittendrin) {category}' => 'Predigerkirche (Musik mittendrin) {category}',
				'Predigerkirche im Pfrundhaus {category}' => 'Predigerkirche im Pfrundhaus {category}',
				'Projekte {category}' => 'Projekte {category}',
				'Reisen durch Zeit und Raum {category}' => 'Reisen durch Zeit und Raum {category}',
				'Rituale im Jahreskreis {category}' => 'Rituale im Jahreskreis {category}',
				'Rorate {category}' => 'Rorate {category}',
				'Seelsorge {category}' => 'Seelsorge {category}',
				'Sekretariat {person-category}' => 'Sekretariat {person-category}',
				'Sigrist/In {person-category}' => 'Sigrist/In {person-category}',
				'Sommergottesdienste {category}' => 'Sommergottesdienste {category}',
				'Sonntagsgottesdienste {category}' => 'Sonntagsgottesdienste {category}',
				'Sonntagskantor {person-category}' => 'Sonntagskantor {person-category}',
				'Sonntagskantorei {category}' => 'Sonntagskantorei {category}',
				'Sozialdienst {person-category}' => 'Sozialdienst {person-category}',
				'Stadtkirche {category}' => 'Stadtkirche {category}',
				'Südsudan {category}' => 'Südsudan {category}',
				'Tagzeitengebet {category}' => 'Tagzeitengebet {category}',
				'Verein Forum Predigerkirche {category}' => 'Verein Forum Predigerkirche {category}',
				'Wandern auf ebenen Pfaden {category}' => 'Wandern auf ebenen Pfaden {category}',
				'Wege des Betens {category}' => 'Wege des Betens {category}',
				'Weihnachten und Neujahr {category}' => 'Weihnachten und Neujahr {category}',
				'Wort und Brot {category}' => 'Wort und Brot {category}',
				'maenner_spirit@kraftort {category}' => 'maenner_spirit@kraftort {category}',
				'maenner_spirit@palmbaum {category}' => 'maenner_spirit@palmbaum {category}',
				'morning_silence@palmbaum {category}' => 'morning_silence@palmbaum {category}',
				'salon_theophil@palmbaum {category}' => 'salon_theophil@palmbaum {category}',
				'Ökumenischer Gottesdienst mit Abendmahl {category}' => 'Ökumenischer Gottesdienst mit Abendmahl {category}',
				'Ökumenischer Gottesdienst {category}' => 'Ökumenischer Gottesdienst {category}',
			),
			'default_value' => array (
				0 => 'post',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56c62e6b12659',
			'label' => 'Source path',
			'name' => 'source_path',
			'type' => 'url',
			'instructions' => 'The full path to DCAPI on a remote site, starting "http://.." and ending "../wp-content/plugins/dcapi/" with a trailing slash',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'clone',
					),
				),
			),
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_571d1f590d16f',
			'label' => 'Source blob',
			'name' => 'source_blob',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'clone',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'location' => 'location',
				'media' => 'media',
				'person' => 'person',
				'post' => 'post',
			),
			'default_value' => array (
				0 => 'post',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_576e8ae5a08e9',
			'label' => 'Source term',
			'name' => 'source_term',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'clone',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'(ohne Kategorie) {category}' => '(ohne Kategorie) {category}',
				'3. bis 8. Klasse {category}' => '3. bis 8. Klasse {category}',
				'Administration {person-category}' => 'Administration {person-category}',
				'Ausflüge und Reisen {category}' => 'Ausflüge und Reisen {category}',
				'Ausstellungen {category}' => 'Ausstellungen {category}',
				'Bildung und Begegnung {category}' => 'Bildung und Begegnung {category}',
				'Chöre {category}' => 'Chöre {category}',
				'Conacher-Orgel {category}' => 'Conacher-Orgel {category}',
				'Der neue Abendgottesdienst {category}' => 'Der neue Abendgottesdienst {category}',
				'Diakonie {category}' => 'Diakonie {category}',
				'Drucksachen {category}' => 'Drucksachen {category}',
				'Eltern-Kind-Singen {category}' => 'Eltern-Kind-Singen {category}',
				'Erwachsene {category}' => 'Erwachsene {category}',
				'Eucharistiefeier {category}' => 'Eucharistiefeier {category}',
				'Feiern im Lebenskreis {category}' => 'Feiern im Lebenskreis {category}',
				'Fiire mit de Chind {category}' => 'Fiire mit de Chind {category}',
				'Flyer {category}' => 'Flyer {category}',
				'Freitagsvesper {category}' => 'Freitagsvesper {category}',
				'Gemeindeseite {category}' => 'Gemeindeseite {category}',
				'Geschichtliches {category}' => 'Geschichtliches {category}',
				'Geselliges {category}' => 'Geselliges {category}',
				'Glanzpunkte {category}' => 'Glanzpunkte {category}',
				'Gottesdienst mit Abendmahl {category}' => 'Gottesdienst mit Abendmahl {category}',
				'Gottesdienst {category}' => 'Gottesdienst {category}',
				'Gottesdienste (Überbegriff) {category}' => 'Gottesdienste (Überbegriff) {category}',
				'Haus zum Palmbaum {category}' => 'Haus zum Palmbaum {category}',
				'Im Pfrundhaus {category}' => 'Im Pfrundhaus {category}',
				'Inscriptum {category}' => 'Inscriptum {category}',
				'Instrumente {category}' => 'Instrumente {category}',
				'Jahresberichte {category}' => 'Jahresberichte {category}',
				'Jahreskreis {category}' => 'Jahreskreis {category}',
				'Jugendtreff {category}' => 'Jugendtreff {category}',
				'Kantor {person-category}' => 'Kantor {person-category}',
				'Kantorei zu Predigern {category}' => 'Kantorei zu Predigern {category}',
				'Katechetin {person-category}' => 'Katechetin {person-category}',
				'Kinder und Jugendliche {category}' => 'Kinder und Jugendliche {category}',
				'Kirche {location-category}' => 'Kirche {location-category}',
				'Kirchenlieder {category}' => 'Kirchenlieder {category}',
				'Kirchenpflege {person-category}' => 'Kirchenpflege {person-category}',
				'Komplet {category}' => 'Komplet {category}',
				'Konfirmation {category}' => 'Konfirmation {category}',
				'Konzerte {category}' => 'Konzerte {category}',
				'Kuhn-Orgel {category}' => 'Kuhn-Orgel {category}',
				'Landeskirche {category}' => 'Landeskirche {category}',
				'Leitbild {category}' => 'Leitbild {category}',
				'Lesegruppe {category}' => 'Lesegruppe {category}',
				'Mittagsgebet {category}' => 'Mittagsgebet {category}',
				'Mushafen {category}' => 'Mushafen {category}',
				'Musical {category}' => 'Musical {category}',
				'Musik mittendrin {category}' => 'Musik mittendrin {category}',
				'Musik {category}' => 'Musik {category}',
				'Musiker {person-category}' => 'Musiker {person-category}',
				'Neuigkeiten {category}' => 'Neuigkeiten {category}',
				'Organist {person-category}' => 'Organist {person-category}',
				'Orgelprojekt {category}' => 'Orgelprojekt {category}',
				'Ostern {category}' => 'Ostern {category}',
				'Pfarrperson {person-category}' => 'Pfarrperson {person-category}',
				'Pfingsten {category}' => 'Pfingsten {category}',
				'Politik {category}' => 'Politik {category}',
				'Prediger Manufaktur {category}' => 'Prediger Manufaktur {category}',
				'Prediger Standorte {location-category}' => 'Prediger Standorte {location-category}',
				'Predigerforum {person-category}' => 'Predigerforum {person-category}',
				'Predigerkirche (Musik mittendrin) {category}' => 'Predigerkirche (Musik mittendrin) {category}',
				'Predigerkirche im Pfrundhaus {category}' => 'Predigerkirche im Pfrundhaus {category}',
				'Projekte {category}' => 'Projekte {category}',
				'Reisen durch Zeit und Raum {category}' => 'Reisen durch Zeit und Raum {category}',
				'Rituale im Jahreskreis {category}' => 'Rituale im Jahreskreis {category}',
				'Rorate {category}' => 'Rorate {category}',
				'Seelsorge {category}' => 'Seelsorge {category}',
				'Sekretariat {person-category}' => 'Sekretariat {person-category}',
				'Sigrist/In {person-category}' => 'Sigrist/In {person-category}',
				'Sommergottesdienste {category}' => 'Sommergottesdienste {category}',
				'Sonntagsgottesdienste {category}' => 'Sonntagsgottesdienste {category}',
				'Sonntagskantor {person-category}' => 'Sonntagskantor {person-category}',
				'Sonntagskantorei {category}' => 'Sonntagskantorei {category}',
				'Sozialdienst {person-category}' => 'Sozialdienst {person-category}',
				'Stadtkirche {category}' => 'Stadtkirche {category}',
				'Südsudan {category}' => 'Südsudan {category}',
				'Tagzeitengebet {category}' => 'Tagzeitengebet {category}',
				'Verein Forum Predigerkirche {category}' => 'Verein Forum Predigerkirche {category}',
				'Wandern auf ebenen Pfaden {category}' => 'Wandern auf ebenen Pfaden {category}',
				'Wege des Betens {category}' => 'Wege des Betens {category}',
				'Weihnachten und Neujahr {category}' => 'Weihnachten und Neujahr {category}',
				'Wort und Brot {category}' => 'Wort und Brot {category}',
				'maenner_spirit@kraftort {category}' => 'maenner_spirit@kraftort {category}',
				'maenner_spirit@palmbaum {category}' => 'maenner_spirit@palmbaum {category}',
				'morning_silence@palmbaum {category}' => 'morning_silence@palmbaum {category}',
				'salon_theophil@palmbaum {category}' => 'salon_theophil@palmbaum {category}',
				'Ökumenischer Gottesdienst mit Abendmahl {category}' => 'Ökumenischer Gottesdienst mit Abendmahl {category}',
				'Ökumenischer Gottesdienst {category}' => 'Ökumenischer Gottesdienst {category}',
			),
			'default_value' => array (
				0 => 'post',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_561578482a98e',
			'label' => 'Linked date/time fields',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'page',
					),
				),
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'post',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5586f5a12e456',
			'label' => 'ACF Date/Time field',
			'name' => 'acf_date_field',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55b514af53307',
			'label' => 'Update ACF Date',
			'name' => 'update_acf_date',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5586f73e2e458',
			'label' => 'ACF Time field',
			'name' => 'acf_time_field',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55b5156c53308',
			'label' => 'Update ACF Time',
			'name' => 'update_acf_time',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_561416961f5df',
			'label' => 'External route',
			'name' => 'external_route',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '!=',
						'value' => 'home',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '!=',
						'value' => 'home-page',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '!=',
						'value' => 'config',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '!=',
						'value' => 'clone',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_560afc1ba279b',
			'label' => 'Generate route',
			'name' => 'generate_route',
			'type' => 'true_false',
			'instructions' => 'If set, generate external route for this item',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 10,
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
		),
		array (
			'key' => 'field_560af587c0309',
			'label' => 'Route prefix',
			'name' => 'route_prefix',
			'type' => 'text',
			'instructions' => 'Optional route prefix to use with this item type',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560afc1ba279b',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'post',
					),
				),
				array (
					array (
						'field' => 'field_560afc1ba279b',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'page',
					),
				),
				array (
					array (
						'field' => 'field_560afc1ba279b',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'search',
					),
				),
			),
			'wrapper' => array (
				'width' => 15,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_560af3e2c0308',
			'label' => 'Route style',
			'name' => 'route_style',
			'type' => 'radio',
			'instructions' => 'Style of external route to this item type',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560afc1ba279b',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'page',
					),
				),
				array (
					array (
						'field' => 'field_560afc1ba279b',
						'operator' => '==',
						'value' => '1',
					),
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'post',
					),
				),
			),
			'wrapper' => array (
				'width' => 15,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'ID' => 'ID',
				'permalink' => 'permalink',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'permalink',
			'layout' => 'vertical',
			'allow_null' => 0,
		),
		array (
			'key' => 'field_554377fab4164',
			'label' => 'Feed settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'home',
					),
					array (
						'field' => 'field_554377a4c107a',
						'operator' => '==',
						'value' => '1',
					),
				),
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'page',
					),
					array (
						'field' => 'field_554377a4c107a',
						'operator' => '==',
						'value' => '1',
					),
				),
				array (
					array (
						'field' => 'field_55e5ee1ee3315',
						'operator' => '==',
						'value' => 'search',
					),
					array (
						'field' => 'field_554377a4c107a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5543780cb4165',
			'label' => 'Feed types',
			'name' => 'feed_types',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 1,
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_55437fb4cd407',
					'label' => 'Feed type',
					'name' => 'feed_type',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_562d42c080a7a',
					'label' => 'Terms field',
					'name' => 'terms_field',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'(anything)' => '(anything)',
					),
					'default_value' => array (
						0 => '(anything)',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_562d436e80a7b',
					'label' => 'Limit field',
					'name' => 'limit_field',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'(anything)' => '(anything)',
					),
					'default_value' => array (
						0 => '(anything)',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_554380eacd40b',
					'label' => 'Source blob',
					'name' => 'source_blob',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 20,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
					),
					'default_value' => array (
						0 => 'post',
					),
					'allow_null' => 0,
					'multiple' => 1,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_55437fc0cd408',
					'label' => 'Ordering',
					'name' => 'order',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 10,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'ASC' => 'ASC',
						'DESC' => 'DESC',
						'(as retrieved)' => '(as retrieved)',
					),
					'default_value' => array (
						0 => 'ASC',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_554380cbcd40a',
					'label' => 'Order by',
					'name' => 'order_by',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 10,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'date' => 'date',
						'title' => 'title',
						'menu_order' => 'menu_order',
						'param/date' => 'param/date',
						'param/order' => 'param/order',
						'relevance' => 'relevance',
					),
					'default_value' => array (
						0 => 'date',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_554383639218a',
					'label' => 'Filtering',
					'name' => 'filter',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Prediger feed filter' => 'Prediger feed filter',
						'standard feed filter' => 'standard feed filter',
					),
					'default_value' => array (
						0 => 'standard page filter',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
			),
		),
		array (
			'key' => 'field_579cb6e91563f',
			'label' => 'Export fields (XLS/CSV/TSV)',
			'name' => 'export_fields_xlscsvtsv',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_554377a4c107a',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_579cb79415641',
			'label' => 'Export fields',
			'name' => 'export_fields',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'sub_fields' => array (
				array (
					'key' => 'field_579cb7d515643',
					'label' => 'Column name',
					'name' => 'column_name',
					'type' => 'text',
					'instructions' => 'Column name to be used in the output spreadsheet. Avoid punctuation and spaces in the name. Each column should have a different name',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_579dd5290b0e9',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'textarea',
					'instructions' => 'Template to create output, use \'blob\' to access blob level, \'feed\' feed level and \'item\' item level fields. Use period to separate levels, eg "{{item.title}}". The output values for the current row can be accessed under \'out\'. One row is written per item in the feed. If the feed is empty, then a single row is output',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'blob',
			),
		),
	),
	'menu_order' => 95,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'author',
		3 => 'format',
		4 => 'page_attributes',
		5 => 'featured_image',
		6 => 'categories',
		7 => 'tags',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56ade92322eae',
	'title' => 'Blob fields',
	'fields' => array (
		array (
			'key' => 'field_553bf4f728d48',
			'label' => 'Fields',
			'name' => 'fields',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'sub_fields' => array (
				array (
					'key' => 'field_56955dd93546a',
					'label' => 'Template',
					'name' => 'template',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57a383b4a46f3',
								'operator' => '!=',
								'value' => '1',
							),
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'clone',
							),
						),
					),
					'wrapper' => array (
						'width' => 35,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 6,
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_553bf53b50eb8',
					'label' => 'Function',
					'name' => 'function',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'template',
							),
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'back end',
							),
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'clone',
							),
							array (
								'field' => 'field_57a383b4a46f3',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'(just copy)' => '(just copy)',
						'build subtitle*' => 'build subtitle*',
						'clean up text' => 'clean up text',
						'contributors list*' => 'contributors list*',
						'convert terms to names' => 'convert terms to names',
						'create hierarchy*' => 'create hierarchy*',
						'create route' => 'create route',
						'get term ID list' => 'get term ID list',
						'get term name list' => 'get term name list',
						'handle categories*' => 'handle categories*',
						'handle gallery' => 'handle gallery',
						'handle image' => 'handle image',
						'handle media image' => 'handle media image',
						'handle page image*' => 'handle page image*',
						'handle person image*' => 'handle person image*',
						'handle post image*' => 'handle post image*',
						'meta data' => 'meta data',
						'process contributors*' => 'process contributors*',
						'process date/time*' => 'process date/time*',
						'process excerpt*' => 'process excerpt*',
						'process homepage feed*' => 'process homepage feed*',
						'process links*' => 'process links*',
						'process location*' => 'process location*',
						'process menu*' => 'process menu*',
						'process permalink*' => 'process permalink*',
						'process redirections*' => 'process redirections*',
					),
					'default_value' => array (
						0 => '(just copy)',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_570e02af219e1',
					'label' => 'Output type',
					'name' => 'output_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57a383b4a46f3',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => 10,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'normal' => 'normal',
						'hidden' => 'hidden',
						'repeat' => 'repeat',
						'postInfo' => 'postInfo',
						'termInfo' => 'termInfo',
						'template' => 'template',
						'back end' => 'back end',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'normal',
					'layout' => 'vertical',
				),
				array (
					'key' => 'field_553bf4cf28d47',
					'label' => 'Output field',
					'name' => 'output_field',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'clone',
							),
							array (
								'field' => 'field_57a383b4a46f3',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_570b9899d2485',
					'label' => 'Output to',
					'name' => 'output_to',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'postInfo',
							),
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'termInfo',
							),
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'template',
							),
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '!=',
								'value' => 'back end',
							),
							array (
								'field' => 'field_57a383b4a46f3',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'blob' => 'blob',
						'feed' => 'feed',
					),
					'default_value' => array (
						0 => 'blob',
					),
					'layout' => 'vertical',
					'toggle' => 0,
				),
				array (
					'key' => 'field_55435282b6fb1',
					'label' => 'Back End',
					'name' => 'back_end',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_570e02af219e1',
								'operator' => '==',
								'value' => 'back end',
							),
							array (
								'field' => 'field_57a383b4a46f3',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'date/status' => 'date/status',
						'info' => 'info',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'info',
					'layout' => 'vertical',
				),
				array (
					'key' => 'field_57a383b4a46f3',
					'label' => 'Hidden',
					'name' => 'hidden',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'blob',
			),
		),
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'dcapiconfig',
			),
		),
	),
	'menu_order' => 97,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;
//---------------------------------

}
?>